var aliases = {
	'Chris': 'Christina',
	'Djeta': 'Djeeta',
	'H.Kyoka': 'H.Kyouka',
	'MG.Shiori': 'M.Shiori',
	'N.Hiyori': 'NY.Hiyori',
	'N.Yui': 'NY.Yui',
	'NNK': 'Neneka',
	'Nyaru': 'NY.Kyaru',
	'NY.Gorda': 'NY.Yui',
	'Peco': 'Pecorine',
	'P.Peco': 'P.Pecorine',
	'Rima': 'Lima',
	'SS.Aoi': 'TS.Aoi',
	'S.Mako': 'S.Makoto',
	'S.Tama': 'S.Tamaki',
	'T.Aoi': 'TS.Aoi',
	'TSAoi': 'TS.Aoi',
	'X.Chris': 'X.Christina',
	'X.Illya': 'X.Ilya'
};